# https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/docs/examples/auth/oauth-external-auth/oauth2-proxy.yaml
# https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth2-proxy-{{ .Release.Name }}
  name: oauth2-proxy-{{ .Release.Name }}
  namespace: kube-system
spec:
  replicas: {{ .Values.oauth.replicas }}
  selector:
    matchLabels:
      app: oauth2-proxy-{{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oauth2-proxy-{{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
        - args:
            - --provider=oidc
            - --upstream=file:///dev/null
            - --http-address=0.0.0.0:4180
            - --auth-logging=1
            - --standard-logging=1
            - --request-logging=1
            - --cookie-secure=true
            - --cookie-csrf-per-request=true
            - --cookie-csrf-expire=5m
            {{- if .Values.oauth.configStrategy | default "args" | eq "args" }}
            {{- /*  Enable use of multiple email domains */}}
            {{- range split "," .Values.oauth.emailDomain }}
            - --email-domain={{ . }}
            {{- end }}
            - --scope={{ .Values.oauth.scope }}
            - --oidc-issuer-url={{ .Values.oauth.oidcIssueUrl }}
            - --cookie-secret={{ .Values.oauth.cookieSecret }}
            - --client-id={{ .Values.oauth.clientId }}
            - --redirect-url={{ .Values.oauth.redirectUrl }}
            - --client-secret={{ .Values.oauth.clientSecret }}
            {{- end }}
            {{- if .Values.oauth.options.allowUnverifiedEmail | default false }}
            - --insecure-oidc-allow-unverified-email
            {{- end }}
          image: "{{ .Values.oauth.image.repository }}:{{ .Values.oauth.image.tag }}"
          imagePullPolicy: "{{ .Values.oauth.image.pullPolicy }}"
          env:
            {{ if .Values.oauth.configStrategy | default "args" | eq "env" }}
            - name: OAUTH2_PROXY_CLIENT_ID
              value: {{ .Values.oauth.clientId | quote }}
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: {{ .Values.oauth.clientSecret | quote }}
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: {{ .Values.oauth.cookieSecret | quote }}
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: {{ .Values.oauth.oidcIssueUrl | quote }}
            - NAME: OAUTH2_PROXY_EMAIL_DOMAINS
              value: {{ .Values.oauth.emailDomain | quote }}
            - NAME: OAUTH2_PROXY_SCOPE
              value: {{ .Values.oauth.scope | quote }}
            {{- end }}
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 128Mi
          name: oauth2-proxy-{{ .Release.Name }}
          ports:
            - containerPort: 4180
              protocol: TCP
---
# apiVersion: policy/v1
# kind: PodDisruptionBudget
# metadata:
#   name: oauth2-proxy-{{ .Release.Name }}
#   namespace: kube-system
# spec:
#   minAvailable: 1
#   selector:
#     matchLabels:
#       app: oauth2-proxy-{{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-{{ .Release.Name }}
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    app: oauth2-proxy-{{ .Release.Name }}
