deployment: {}
service: {}

tlsCert:
  issuer:
    name: ""
    kind: ""
    group: ""
    # name: letsencrypt-prod
    # kind: ClusterIssuer
    # group: cert-manager.io
  name: ""
  secretName: ""

ingress:
  host: "helloworld.np.wachs.work"
