apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "general-service.fullname" . }}
  labels:
    {{- include "general-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "general-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "general-service.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "general-service.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- range .Values.initContainers }}
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy | default "IfNotPresent" }}
          {{- with .command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .env.literal .env.fromConfigMaps .env.fromSecrets }}
          env:
            {{- range $key, $value := .env.literal }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .env.fromConfigMaps }}
            {{- $configMapName := .configMapName }}
            {{- range .keys }}
            - name: {{ .envName | default .key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: {{ .key }}
            {{- end }}
            {{- end }}
            {{- range .env.fromSecrets }}
            {{- $secretName := .secretName }}
            {{- range .keys }}
            - name: {{ .envName | default .key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .key }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- with .volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .securityContext }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          {{- else }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "general-service.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          {{- if or .Values.env.literal .Values.env.fromConfigMaps .Values.env.fromSecrets }}
          env:
            {{- range $key, $value := .Values.env.literal }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range .Values.env.fromConfigMaps }}
            {{- $configMapName := .configMapName }}
            {{- range .keys }}
            - name: {{ .envName | default .key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $configMapName }}
                  key: {{ .key }}
            {{- end }}
            {{- end }}
            {{- range .Values.env.fromSecrets }}
            {{- $secretName := .secretName }}
            {{- range .keys }}
            - name: {{ .envName | default .key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ .key }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
