{{- if and .Values.rbac.create .Values.rbac.clusterRole.rules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "claw.fullname" . }}
  labels:
    {{- include "claw.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  {{- toYaml .Values.rbac.clusterRole.rules | nindent 2 }}
{{- end }}
