{{- if and .Values.rbac.create .Values.rbac.role.rules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "claw.fullname" . }}
  labels:
    {{- include "claw.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "claw.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "claw.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
