apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Release.Name }}-tls-crt-prod"
  namespace: "{{ .Values.deployment.metadata.namespace }}"
spec:
  secretName: {{ include "gated-service.secretName" . }}
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  dnsNames:
    - "{{ .Values.ingress.host }}"
  issuerRef:
    name: "{{ .Values.tlsCert.issuer.name }}"
    kind: "{{ .Values.tlsCert.issuer.kind }}"
    group: "{{ .Values.tlsCert.issuer.group }}"
