apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatgpt-oauth
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-rps: "20"
spec:
  ingressClassName: nginx
  rules:
    - host: chatgpt.wachs.work
      http:
        paths:
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy-chatgpt
                port:
                  number: 4180
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatgpt
  namespace: public
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - chatgpt.wachs.work
      secretName: chatgpt-wachs-work-tls-cert-prod
  rules:
    - host: chatgpt.wachs.work
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chatgpt-svc
                port:
                  number: 80
