# https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/docs/examples/auth/oauth-external-auth/oauth2-proxy.yaml
# https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy-chatgpt
  name: oauth2-proxy-chatgpt
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy-chatgpt
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy-chatgpt
    spec:
      restartPolicy: Always
      containers:
        - args:
            - --provider=oidc
            - --email-domain=
            - --scope=openid profile email
            - --upstream=file:///dev/null
            - --http-address=0.0.0.0:4180
            - --redirect-url=
            - --oidc-issuer-url=
            - --cookie-secret=
            - --client-id=
            - --client-secret=
            # The following flag is removed due to potential exploit that allows unverified email addresses
            #- --insecure-oidc-allow-unverified-email
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 128Mi
          name: oauth2-proxy-chatgpt
          ports:
            - containerPort: 4180
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy-chatgpt
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    k8s-app: oauth2-proxy-chatgpt
