---
apiVersion: v1
kind: Service
metadata:
  name: chatgpt-svc
  namespace: public
spec:
  selector:
    app: chatgpt
  type: ClusterIP
  ports:
    - name: chatgpt
      protocol: TCP
      port: 80
      targetPort: 3000
